; Generated by CompilerKit
; Target: 64-bit

.section __TEXT,__text,regular,pure_instructions

.globl _add
.p2align 2
_add:
.cfi_startproc
	sub sp, sp, #16	; allocate 16 bytes
.Lentry:
	add w0, w2, w1	; add
	add sp, sp, #16	; deallocate stack frame
	ret	; return
.cfi_endproc

.globl _main
.p2align 2
_main:
.cfi_startproc
	str x29, [sp, #-16]!	; save FP and LR with pre-decrement
	str x30, [sp, #8]
	mov x29, sp	; set up frame pointer
	sub sp, sp, #64	; allocate 64 bytes
.Lentry:
	mov w0, #10	; load constant 10
	mov w1, #20	; load constant 20
	mov w0, w0	; arg 0
	mov w1, w1	; arg 1
	bl _add	; branch with link
	mov w2, w0	; get result
	mov w0, w2	; return value
	mov sp, x29	; restore stack pointer
	ldr x29, [sp], #16	; restore FP and LR with post-increment
	ldr x30, [sp, #-8]
	ret	; return
.cfi_endproc
