; Generated by CompilerKit
; Target: 64-bit

.section __TEXT,__text,regular,pure_instructions

.globl _main
.p2align 2
_main:
.cfi_startproc
	str x29, [sp, #-16]!	; save FP and LR with pre-decrement
	str x30, [sp, #8]
	mov x29, sp	; set up frame pointer
	sub sp, sp, #64	; allocate 64 bytes
entry:
	mov w0, wzr	; load zero
	mov w1, #1	; load constant 1
	b L0	; unconditional jump
L0:
	mov w0, #5	; load constant 5
	cmp w2, w0	; compare
	cset x1, le	; conditional set
	tst x1, x1	; test condition
	b.ne L1	; branch if true
	b L2	; branch if false
L1:
	add w0, w2, w1	; add
	mov w3, #1	; load constant 1
	add w4, w1, w3	; add
	b L0	; unconditional jump
L2:
	mov sp, x29	; restore stack pointer
	ldr x29, [sp], #16	; restore FP and LR with post-increment
	ldr x30, [sp, #-8]
	ret	; return
.cfi_endproc
