; Generated by CompilerKit
; Target: 64-bit

.section __TEXT,__text,regular,pure_instructions

.globl _main
.p2align 2
_main:
.cfi_startproc
	str x29, [sp, #-16]!	; save FP and LR with pre-decrement
	str x30, [sp, #8]
	mov x29, sp	; set up frame pointer
	sub sp, sp, #64	; allocate 64 bytes
.Lmain_entry:
	mov x0, x0	; arg 0
	bl _printf	; branch with link
	mov w1, w0	; get result
	mov w2, #42	; load constant 42
	mov x0, x3	; arg 0
	mov w1, w2	; arg 1
	bl _printf	; branch with link
	mov w4, w0	; get result
	mov w5, wzr	; load zero
	mov w0, w5	; return value
	mov sp, x29	; restore stack pointer
	ldr x29, [sp], #16	; restore FP and LR with post-increment
	ldr x30, [sp, #-8]
	ret	; return
.cfi_endproc
